blog/WinterBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
]

blog/blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name="blog"
urlpatterns = [
	url(r'^admin_tools/$', views.admin_tools, name="admin_tools"),
	url(r'^alter/$', views.alter, name="alter"),
	url(r'^post/(?P<post_id>[0-9]+)', views.comment, name="comment"),
	url(r'^delete/(?P<type>[post|comment]+)', views.delete, name="delete"),
	url(r'^discover/$', views.discover, name="discover"),
	url(r'^feed/$', views.feed, name="feed"),
	url(r'^follow/(?P<username>[a-zA-Z0-9_.+-]+)$', views.follow, name="follow"),
	url(r'^profile/edit/(?P<username>[a-zA-Z0-9_.+-]+)/$', views.edit, name="edit"),
	url(r"^$", views.home, name="home"),
	url(r'^signup/$', views.signup, name="signup"),
	url(r'^pdf/$', views.pdf, name="pdf"),
	url(r'^post/$', views.post, name="post"),
	url(r'^profile/(?P<username>[a-zA-Z0-9_.+-]+)/$', views.profile, name="profile"),
	url(r'^login/$', views.ulogin, name="ulogin"),
	url(r'^unfollow/(?P<username>[a-zA-Z0-9_.+-]+)$', views.unfollow, name="unfollow"),
	url(r'^xlsx/$', views.xlsx, name="xlsx"),
	]

# This will allow us to add static and media urls as well as specify where files should be uploaded to.
# DEBUG == True requirement because this is unsuitable for production.
statics = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
medias = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
extras = statics + medias
if settings.DEBUG == True:
    urlpatterns += extras

blog/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os

from PIL import Image

from django.db import models
from django.conf import settings
from django.core.files import File
from django.contrib.auth.models import User


# this function is passed to the upload_to argument of the dp ImageField of Blogger
# to allow each user to have their own folder for DPs.
def user_directory_path(instance, filename):
    return "{0}/{1}".format(instance.user.username, filename)


class Blogger(models.Model):
    user = models.OneToOneField(User, models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True, default="")
    last_name = models.CharField(max_length=100,  blank=True, default="")
    bhawan = models.CharField(max_length=30, blank=True, default="")
    following = models.ManyToManyField(User, related_name="following")
    dp = models.ImageField(upload_to=user_directory_path, default="db.jpeg")
    # username and email are already covered by the default user class i.e. the one-to-one relation here.

    def __str__(self):
        return self.user.username

    def resize(self):
        # Resize operation to create a 250 x 250 px image.
        i_path = str(os.path.join(settings.MEDIA_ROOT, self.dp.name))
        im = Image.open(i_path)
        im = im.resize((250,250))
        im.save(i_path)


class Post(models.Model):
    date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField(max_length=100)
    date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    # when working with the Django Database API use post.comments instead of post.comment_set,
    # that's what the related name is for!

    def __str__(self):
            return self.post.title

blog/blog/views.py
                                # VIEW IMPORTS

# For python 2 vs 3 compatibility
from __future__ import unicode_literals

# Standard Library Imports
import re
import os
import io
import logging
from datetime import datetime

# Django Settings and Functions to Return to clients
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

# Django Authorization
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Django Messages
from django.contrib import messages

# Code That I Wrote
from .models import Blogger, Post, Comment
from .externalfunctions import new_user_invalid, ordered_feed, generate_xlsx, generate_pdf, inactive_validation


                                # SET UP LOGGING SYSTEM

INFOPATH = os.path.join(settings.BASE_DIR, "blog/logs/INFO.log")
DEBUGPATH = os.path.join(settings.BASE_DIR, "blog/logs/DEBUG.log")
LOG_SETTINGS = {
    'version':1,
    'disable_existing_loggers':False, # to keep the Django logging system
    'formatters':{
        'default': {
            'format':'TIME: %(asctime)s\nLEVEL: %(levelname)s\nMESSAGE: %(message)s\n'
        }
    },
    'handlers':{
        'info':{
            'level':'INFO',
            'formatter':'default',
            'class':'logging.FileHandler',
            'filename':INFOPATH
        },
        'debug':{
            'level':'DEBUG',
            'formatter':'default',
            'class':'logging.FileHandler',
            'filename':DEBUGPATH,
            'mode':'w'
        }
        # until and unless someone adds some debug messages, the two will be the same.
    },
    'loggers':{
        'viewlog':{
            'level':'INFO',
            'handlers':['info','debug'],
            'propagate':True
        }
    }
}


logging.config.dictConfig(LOG_SETTINGS)
viewlog = logging.getLogger("viewlog")

"""
if you are getting any errors regarding the logging system, first make sure that
the files/folder: <BASE_DIR>/blog/logs/DEBUG.log and <BASE_DIR>/blog/logs/DEBUG.log exist,
else, make them.
"""

                                # VIEW FUNCTIONS


# Visible view where users can login or sign up
def home(request):
    if request.user:
        logout(request)
        viewlog.info("User {} has logged out.".format(request.user.username))
    context = None
    return render(request, 'blog/home.html', context)


# Hidden view for signing up new users and logging them in
def signup(request):
    username = request.POST['username'].lower()
    password = request.POST['password']
    p_verification = request.POST['password_verifier']
    email = request.POST['email_id']

    credentials = [username, password, p_verification, email]

    invalid = new_user_invalid(credentials)

    if not invalid:
        u = User(username=username, email=email)
        u.set_password(password)
        u.save()

        b = Blogger(user=u)
        b.save()

        user = authenticate(username=u.username, password=u.password)
        login(request, user)

        return redirect('blog:profile', permanent=True, username=user.username)

    else:
        messages.add_message(request, messages.WARNING, invalid)
        return redirect('blog:home')


# Hidden view for logging users in
def ulogin(request):
    data = request.POST
    username = data['username'].lower()
    password = data['password']

    # SQL injection is already taken care of by Django, this is just an easter egg.
    if username == "1'or'1'='1":
        messages.add_message(request, messages.ERROR, 'lol, nice try turd.')
        viewlog.warning("An idiot tried to log in.")
        return redirect('blog:home')

    user = authenticate(username=username, password=password)

    if user == None:
        if inactive_validation(username=username, password=password):
        # the user is in the db but is currently 'inactive' i.e. banned.
            messages.add_message(request, messages.ERROR, 'You have been banned!!!')
            return redirect('blog:home')
        else:
        # user not in the db/credentials are wrong.
            messages.add_message(request, messages.ERROR, 'invalid login credentials!')
            viewlog.warning("Failed login attempt for username: {}".format(username))
            return redirect('blog:home')
    else:
        login(request, user)
        viewlog.info("Successful login attempt for username: {}".format(username))
        return redirect('blog:profile', permanent=True, username=user.username)


# Visible view for the user's posts feed
@login_required
def feed(request):
    feedable =  []
    for u in request.user.blogger.following.all():
        for p in u.post_set.all():
            feedable.append(p)
    feed = ordered_feed(feedable)
    context = {"feed":feed}
    viewlog.info("User: {} visited their feed".format(request.user.username))
    return render(request, "blog/feed.html", context)


# Visible view for the user's profile page
@login_required
def profile(request, username):
    profile_person = User.objects.get(username=username)
    joined = profile_person.date_joined.strftime("%b %d %Y")
    context = {"user":profile_person, "posts":profile_person.post_set.order_by('-date')}
    viewlog.info("User: {} visited their profile".format(request.user.username))
    return render(request, 'blog/profile.html', context)


# Visible view for allowing the user to edit their profile
@login_required
def edit(request, username):
    if request.method == "GET":
    # give the user a fresh page
        if request.user.username == username:
            viewlog.info("User: {} has opened their profile edit panel".format(request.user.username))
            return render(request, 'blog/edit.html', None)
        else:
        # don't allow users to edit other users' profiles
            if not request.user.is_superuser:
                messages.add_message(request, messages.WARNING, "You are not allowed to edit other's profiles! The admin has been notified of this event.")
                viewlog.warning("User: {} has attempted to edit {}'s profile!!!".format(request.user.username, username))
            return redirect('blog:profile', username=username)

    elif request.method == "POST":
    # make sure that the entered credentials are acceptable and that the user has a blogger table in the database
        data = request.POST
        username = request.user.username
        user = User.objects.get(username=username)

        try:
        # this will raise an error if the blogger table doesn't exist
            user.blogger.first_name = data['first_name'].title()

        except:
            b = Blogger.objects.get_or_create(user=user)

        finally:
            if data['first_name']:
                user.blogger.first_name = data['first_name'].title()
            else:
                user.blogger.first_name = ""

            if data['last_name']:
                user.blogger.last_name = data['last_name'].title()
            else:
                user.blogger.last_name = ""

            if data['bhawan']:
                user.blogger.bhawan = data['bhawan'].title()
            else:
                user.blogger.bhawan = ""

            if data['email'] and re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", data['email'] ):
                user.email = data['email']

            else:
                messages.add_message(request, messages.ERROR, 'you must have a valid email id')
                viewlog.warning("USER: {} has failed to edit their profile. F12 suspected.".format(request.user.username))
                return redirect('blog:edit', request.user.username)


            try:
                if request.FILES["profile_pic"]:
                    f = request.FILES["profile_pic"]
                    user.blogger.dp = f
                    user.blogger.save()
                    user.blogger.resize()
                    # saving once to take f from being an InMemoryUploadedFile object to a saved file in the right folder
            except:
                pass

            finally:
                user.blogger.save()
                user.save()
                viewlog.info("User: {} has successfully edited their profile".format(request.user.username))
                return redirect('blog:profile', request.user.username)


# Hidden view for the follow functionality
@login_required
def follow(request, username):
    to_add = User.objects.get(username=username)
    u = request.user
    u.blogger.following.add(to_add)
    u.save()
    viewlog.info("User: {} has followed {}".format(request.user.username, username))
    return redirect('blog:profile', username)


# Hidden view for the unfollow functionality
@login_required
def unfollow(request, username):
    to_rem = User.objects.get(username=username)
    u = request.user
    u.blogger.following.remove(to_rem)
    u.save()
    viewlog.info("User: {} has unfollowed {}".format(request.user.username, username))
    return redirect('blog:profile', username)


# Visible view for the 'discover other users' functionality
@login_required
def discover(request):
    all_users = User.objects.all()
    all_unfollowed_users = []
    for user in all_users:
        if user not in request.user.blogger.following.all() and user != request.user:
            all_unfollowed_users.append(user)
    context = {"all_unfollowed_users":all_unfollowed_users}
    viewlog.info("User: {} visited their discover page".format(request.user.username))
    return render(request, 'blog/discover.html', context)


# Visible view where the user can write a Post and then post it
@login_required
def post(request):

    if request.method == "GET":
        viewlog.info("User: {} visited the post page".format(request.user.username))
        return render(request, 'blog/post.html')

    if request.method == "POST":
        post_data = request.POST

blog/blog/templates/blog/admin_tools.html
{% extends "blog/base.html" %}

{% block content %}

<form action="{% url 'blog:alter' %}" method="post">
  {% csrf_token %}

<br><br>

<hr>
  <div class="container">
    <table class="center-align">
      <tr class="center-align">
        <td class="center-align"><b> Generate .xlsx File </b></td>
        <td class="center-align"><b> Generate .pdf File </b></td>
        <td class="center-align"><b> Django Admin Panel</b></td>
      </tr>
      <tr class="center-align">
        <td class="center-align"><a href="{% url 'blog:xlsx' %}" class="btn hoverable green">Generate</a></td>
        <td class="center-align"><a href="{% url 'blog:pdf' %}" class="btn hoverable red">Generate</a></td>
        <td class="center-align"><a href="/admin" class="btn hoverable blue darken-3"> I Am Root! </a></td>
      </tr>
    </table>
  </div>
<hr>

<br><br>

  <div>
    <h3 class="center-align"> Current Users </h3>
    <br>
    <table class="center-align">
        <thead>
          <th> Username </th>
          <th> First Name </th>
          <th> Last Name </th>
          <th> Bhawan </th>
          <th> E-Mail </th>
          <th colspan="2"> Status </th>
        </thead>
        {% for user in users %}
        <tr>
          <td> {{user.username}} </td>
          <td> {{user.blogger.first_name}} </td>
          <td> {{user.blogger.last_name}} </td>
          <td> {{user.blogger.bhawan}} </td>
          <td> {{user.email}} </td>
          <td class="{% if user.is_superuser %} blue-text {% else %} {% if user.is_active %} green-text {% else %} red-text {% endif %} {% endif %}">
            {% if user.is_superuser %} ADMIN {% else %}
            {% if not user.is_superuser %}<input type="checkbox", name="{{ user.username }}" id="{{ forloop.counter }}"/>
               <label for="{{ forloop.counter }}"></label> {% endif %}{% if user.is_active %} Active {% else %} Banned {% endif %} {% endif %}</td>
        </tr>
        {% endfor %}
    </table>
  </div>

<br><br>

<p class="center"><input type="submit" value="alter status" class="btn hoverable blue darken-3"/></p>

<br><br>
</form>
{% endblock %}

blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html>

<head>
  {% load static %}
  <title> BackEnd's Blog </title>
  <link rel="stylesheet" href="{% static 'materialize.min.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body class="grey lighten-2">

    <!-- Navbar -->
        <nav class="blue darken-3">
         <div class="nav-wrapper">
           <a class="brand-logo">BackEnd's Blog</a>
           <ul id="nav-mobile" class="right hide-on-med-and-down">
             <li><a href="{% url 'blog:feed' %}"> Feed </a></li>
             <li><a href="{% url 'blog:post' %}"> Post </a></li>
             <li><a href="{% url 'blog:profile' request.user.username %}"> Profile </a></li>
             <li><a href="{% url 'blog:discover' %}"> Discover </a></li>
             {% if request.user.is_superuser %}
              <li><a href="{% url 'blog:admin_tools' %}"> Admin Tools </a><li>
             {% endif %}
             <li><a href="{% url 'blog:home' %}"> Logout </a></li>
           </ul>
         </div>
        </nav>

  {% if messages %}
    {% if message.tags == "success" %}
      <p class="green-text"> {{message}} </p>
    {% else %}
      <p class="red-text"> {{message}} </p>
    {% endif %}
  {% endif %}

  {% block content %}
  {% endblock %}
</body>

</html>

blog/blog/templates/blog/comment.html
{% extends "blog/base.html" %}

{% block content %}

<br><br>

<div class="row container" class="post_div">
  <table style="border:dashed">

    <tr class="post_header">
      <td><h2 class="left-align"> {{post.title}} </h2>  <h5 class="left-align"> {{post.date }} </h5></td>
    </tr>

    <tr class="grey lighten-4">
      <td class="post_content"> {{post.content}} </td>
    </tr>

    <tr class="grey lighten-4">
      <td class="post_content">
        <p class="right-align">
          ~ {% if post.user.blogger.first_name != "?" %} {{post.user.blogger.first_name}} {% endif %} {% if post.user.blogger.last_name != "?" %} {{post.user.blogger.last_name}} {% endif %}
          {% if post.user.blogger.first_name == "?"  and post.user.blogger.last_name == "?" %} {{post.user.username}} {% endif %}
        </p>
      </td>
    </tr>
    {% if request.user == post.user %}
    <tr class="grey lighten-4">
      <td class="right-align">
        <!-- Delete Function -->
        <form method="post" action="{% url 'blog:delete' 'post' %}">
        {% csrf_token %}
          <input type="hidden" name="post_id" value="{{post.id}}" />
          <input type="submit" class="btn-small red" value="delete" />
        </form>
      </td>
    </tr>
    {% endif %}
  <table>
 <br>
</div>

<br>
<div class="row grey lighten-4">
  <br>
  <h3> Post a Comment: </h3>
  <p class="grey-text"> 100 characters max </p>
  <form method="post" action="{% url 'blog:comment' post.id %}">
  {% csrf_token %}
    <input type="text" maxlength=100 name="comment" />
    <p class="center-align"><input type="submit" value="comment" class="btn hoverable" /></p>
    <br>
  </form>
</div>

<br>
<div>
  <h3> Comments: </h3>
  {% for comment in post.comments.all %}
  <table class="grey lighten-4">
      <tr>
        <td> {{comment.content}} </td>
      </tr>
      <tr>
        <td>
        <p class="right-align">
          ~ {% if comment.user.blogger.first_name != "?" %} {{comment.user.blogger.first_name}} {% endif %} {% if comment.user.blogger.last_name != "?" %} {{comment.user.blogger.last_name}} {% endif %}
          {% if comment.user.blogger.first_name == "?"  and comment.user.blogger.last_name == "?" %} {{comment.user.username}} {% endif %}
        </p>
        <p class="right-align"> {{comment.date}} </p>
      </td>
      </tr>
      <tr>
        {% if request.user == comment.user %}
        <tr class="grey lighten-4">
          <td class="right-align">
            <!-- Delete Function -->
            <form method="post" action="{% url 'blog:delete' 'comment' %}">
            {% csrf_token %}
              <input type="hidden" name="comment_id" value="{{comment.id}}" />
              <input type="submit" class="btn-small red" value="delete" />
            </form>
          </td>
        </tr>
        {% endif %}
      </tr>
  </table>
  <br>
  {% endfor %}
  {% if no_comments %}
    <td><h5> None </h5></td>
  {% endif %}
</div>

{% endblock %}

blog/blog/templates/blog/discover.html
{% extends "blog/base.html" %}

{% block content %}

  <br>

  <h2> Other Users: </h2>

  <br><br>

  <div class="container">
      <table>
        <thead class="grey lighten-1">
          <td><b> Username </b></td>
          <td><b> First Name </b></td>
          <td><b> Last Name </b></td>
          <td><b> Bhawan </b></td>
        </thead>

        {% for user in all_unfollowed_users %}
                <tr class="grey lighten-3">
                  <td><a href="{% url 'blog:profile' user.username %}"> {{user.username}} </a></td>
                  <td> {{user.blogger.first_name}} </td>
                  <td> {{user.blogger.last_name}} </td>
                  <td> {{user.blogger.bhawan}} </td>
                </tr>
        {% endfor %}

      </table>


  </div>
{% endblock %}

blog/blog/templates/blog/feed.html
{% extends "blog/base.html" %}

{% block content %}

<br><br>

  {% for post in feed %}
  <div class="row container" class="post_div">
    <table style="border:dashed">
      <tr class="post_header">
        <td><h2 class="left-align"> {{post.title}} </h2>  <h5 class="left-align"> {{post.date }} </h5></td>
      </tr>

      <tr class="grey lighten-4">
        <td class="post_content"> {{post.content}} </td>
      </tr>

      <tr class="grey lighten-4">
        <td class="post_content">
          <p class="right-align">
            ~ {% if post.user.blogger.first_name != "?" %} {{post.user.blogger.first_name}} {% endif %} {% if post.user.blogger.last_name != "?" %} {{post.user.blogger.last_name}} {% endif %}
            {% if post.user.blogger.first_name == "?"  and post.user.blogger.last_name == "?" %} {{post.user.username}} {% endif %}
          </p>
          <br>
          <a href="{% url 'blog:comment' post.id %}"> comment </a>
        </td>
      </tr>

    <table>
    <br>
  </div>
  {% endfor %}

{% endblock %}

blog/blog/templates/blog/home.html
<!DOCTYPE html>
<html>

<head>
  <title> BackEnd's Blog </title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'materialize.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'home_page.css' %}" type="text/css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body class="grey lighten-2">


  <!-- Header -->
  <div class="container center-align">
      <h1> Backend's Blog </h1>
  </div>

  <!-- Table for Organisation -->

  <table cellspacing="500">
   <tr>

      <!-- Signup Form -->
      <td class="blue lighten-4">
      <form action="{% url 'blog:signup' %}" method="post">
       {% csrf_token %}
       <p class="center"> Sign Up </p>

       {% if messages %}
       <p class="red-text center-align">{% for message in messages %} {% if forloop.counter == 1 and message.tags == 'warning'%} {{message}}  {% endif %} {% endfor %}</p>
       {% endif %}

        <label for="username"> Username: </label>
          <input type="text" name="username" maxlength=100 required/>
        <br>
        <label for="password"> Password: </label>
          <input type="password" name="password" maxlength=100 required/>
        <br>
        <label for="password_verifier"> Password Again: </label>
          <input type="password" name="password_verifier" maxlength=100 required/>
        <br>
        <label for="email_id"> Email Id: </label>
          <input type="email" name="email_id" required/>
        <p class="center-align"><input type="submit" value="sign up" class="blue btn" /></p>
        <!-- !!!! Add waves ripple effect to the buttons -->
      </form>
      </td>

      <!-- !!!! Add cell spacing -->

      <!-- Login Form -->
      <td class="green lighten-3 accent-1">
      <form action="{% url 'blog:ulogin' %}" method="post">
       {% csrf_token %}
       <p class="center"> Login </p>

       <!-- display error message if entered login credentials are incorrect -->
       {% if messages %}
       <p class="red-text center-align">{% for message in messages %} {% if forloop.counter == 1 and message.tags == 'error'%} {{message}}  {% endif %} {% endfor %}</p>
       {% endif %}

        <label for="username"> Username: </label>
          <input type="text" name="username" required/>
        <br>
        <label for="password"> Password: </label>
          <input type="password" name="password" required/>

        <br><br><br><br><br><br><br><br><br>
        <p class="center-align"><input type="submit" value="login" class="green btn" /></p>
        <!-- !!!! Add waves ripple effect to the buttons -->
      </form>
      </td>

   </tr>
  <table>


</body>

</html>

blog/blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'post_page.css' %}" type"text/css" />

<br><br><br>

<form action="{% url 'blog:post' %}" method="post" id="post">
{% csrf_token %}

  <div class="container center-align">
    <table style="width:100%">

      <tr class="blue darken-4">
        <td>
          <label for="title">Title</label>
          <input type="text" name="title" id="title" maxlength="50" required/>
        </td>
      </tr>

      <tr class="grey lighten-4" height="300">
        <td>
          <textarea name="content" form="post" id="content" maxlength="1000"></textarea>
        </td>
      </tr>

    </table>
  </div>

<br><br>

<div class="container center-align">
  <input type="submit" class="btn-large hoverable blue darken-4" value="Post"/>
</div>

<br>

</form>

{% endblock %}

blog/blog/templates/blog/profile.html
{% extends "blog/base.html"  %}

{% block content %}

{% load static %}
<br><br><br>


<div class="row">

  <div class="col s1"> <!-- just to give some space --> </div>

  <div class="col s2">

    {% if user.blogger.dp %}
      <img src="{{user.blogger.dp.url}}"/>
    {% else %}
      <img src="{% static 'db.jpeg' %}"/>
    {% endif %}

    {% if request.user != user %}
      {% if user in request.user.blogger.following.all %}
        <a href="{% url 'blog:unfollow' user.username %}" class="btn-small"> UnFollow </a>
      {% else %}
        <a href="{% url 'blog:follow' user.username %}" class="btn-small"> Follow </a>
      {% endif %}
    {% endif %}
  </div>

  <div class="col s1"> <!-- just to give some space --> </div>

  <div class="col s8">
    <table>
      <tr>
        <td class="grey lighten-1"> Username </td>
        <td class="grey lighten-1"> {{user.username}} </td>
      </tr>
      <tr>
        <td class="grey lighten-2"> First Name </td>
        <td class="grey lighten-2"> {{user.blogger.first_name}} </td>
      </tr>
      <tr>
        <td class="grey lighten-1"> Last Name </td>
        <td class="grey lighten-1"> {{user.blogger.last_name}} </td>
      </tr>
      <tr>
        <td class="grey lighten-2"> Bhawan </td>
        <td class="grey lighten-2"> {{user.blogger.bhawan}} </td>
      </tr>
      <tr>
        <td class="grey lighten-1"> Email </td>
        <td class="grey lighten-1"> {{user.email}} </td>
      </tr>
    </table>
    {% if user == request.user %}
        <!-- edit page option -->
        <div class="right-align">
          <a class="btn-small" href="{% url 'blog:edit' user.username %}"> edit </a>
        </div>
    {% endif %}

  </div>

</div>

<br><br>

<div class="row">
  <h3> Following </h3>
  <table>
    <thead>
      <td> Username </td>
      <td> First Name </td>
      <td> Last Name </td>
      <td> Bhawan </td>
    </thead>

    {% for u in user.blogger.following.all %}
      <tr>
        <td><a href="{% url 'blog:profile' u.username %}"> {{u.username}} </a></td>
        <td> {{u.blogger.first_name}} </td>
        <td> {{u.blogger.last_name}} </td>
        <td> {{u.blogger.bhawan}} </td>
      </tr>
    {% endfor %}
  </table>
</div>

<br>

<h3> Posts </h3>

{% for post in posts %}
<div class="row container">
  <table style="border:dashed">
    <tr>
      <td><h4 class="left-align"> {{post.title}} </h4>  <h6 class="left-align"> {{post.date }} </h6></td>
    </tr>

    <tr class="grey lighten-4">
      <td> {{post.content}} </td>
      <td class="right-align"><a href="{% url 'blog:comment' post.id %}"> comment </a></td>
    </tr>
  <table>
  <br>
</div>
{% endfor %}

{% endblock %}